version: '3.4'

services:
  postgres:
    image: postgres
    container_name: "jitpay_postgres"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jitpay
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data